#!/bin/sh
# Pre-remove script for class-website

# Stop uhttpd
/etc/init.d/uhttpd stop 2>/dev/null

# Remove web files
rm -rf /www/class-website

# Reset uhttpd config
uci delete uhttpd.main.home 2>/dev/null
uci commit uhttpd